/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author alan
 */
public class MedicineAssignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicineAssignJPanel
     */
    private Application application;
    
    public MedicineAssignJPanel() {
        initComponents();
        this.application = application;
//        populate();
    }

    MedicineAssignJPanel(Application application) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obBox = new javax.swing.JComboBox<>();
        medBox = new javax.swing.JComboBox<>();
        btnAssign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        obBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                obBoxItemStateChanged(evt);
            }
        });
        obBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obBoxActionPerformed(evt);
            }
        });
        add(obBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 180, 90));

        medBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medBoxActionPerformed(evt);
            }
        });
        add(medBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, 90));

        btnAssign.setText("Assign");
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void medBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medBoxActionPerformed
        // TODO add your handling code here:
        Observation o = (Observation) obBox.getSelectedItem();
        Medicine m = (Medicine) medBox.getSelectedItem();
        
        o.setMedication(m);
    }//GEN-LAST:event_medBoxActionPerformed

    private void obBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obBoxActionPerformed

    private void obBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_obBoxItemStateChanged
        // TODO add your handling code here:
        Observation o = (Observation) obBox.getSelectedItem();
        
        if(o.getMedication() != null) {
            jLabel1.setText(o.getMedication().getMedicineName());
        }
    }//GEN-LAST:event_obBoxItemStateChanged
    
//    public void populate() {
//        
//        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
//        
//        ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();
//        
//        for(Observation o: observations) {
//            obBox.addItem(o);
//        }
//        
//        for(Medicine med: medicines) {
//            medBox.addItem(med);
//        }
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> medBox;
    private javax.swing.JComboBox<String> obBox;
    // End of variables declaration//GEN-END:variables
}
