/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author alan
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private Person person;
    public MainJFrame() {
        initComponents();
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        viewPanel = new javax.swing.JPanel();
        viewNUID = new javax.swing.JLabel();
        viewFirstName = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewPersonalPhone = new javax.swing.JLabel();
        viewPersonalEmail = new javax.swing.JLabel();
        viewStreet = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viewOfficeEmail = new javax.swing.JLabel();
        viewPermanentStreet = new javax.swing.JLabel();
        UserFormPanel = new javax.swing.JPanel();
        fieldID = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SaveBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldCollegeName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldStreet = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldOfficeEmail = new javax.swing.JTextField();
        fieldOfficePhone = new javax.swing.JTextField();
        address2 = new javax.swing.JLabel();
        fieldPermanentStreet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewNUID.setText("nuid");
        viewPanel.add(viewNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        viewFirstName.setText("first name");
        viewPanel.add(viewFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        viewLastName.setText("last name");
        viewPanel.add(viewLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        viewCollegeName.setText("college name");
        viewPanel.add(viewCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        viewPersonalPhone.setText("personal phone");
        viewPanel.add(viewPersonalPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        viewPersonalEmail.setText("personal email");
        viewPanel.add(viewPersonalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        viewStreet.setText("address");
        viewPanel.add(viewStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        viewOfficePhone.setText("office phone");
        viewPanel.add(viewOfficePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        viewOfficeEmail.setText("office email");
        viewPanel.add(viewOfficeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        viewPermanentStreet.setText("permanent address");
        viewPanel.add(viewPermanentStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        jSplitPane1.setRightComponent(viewPanel);

        UserFormPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDActionPerformed(evt);
            }
        });
        UserFormPanel.add(fieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 324, 147, -1));
        UserFormPanel.add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 358, 147, -1));

        jLabel1.setText("NUID");
        UserFormPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 329, -1, -1));

        jLabel2.setText("First Name");
        UserFormPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 362, -1, -1));

        SaveBTN.setText("Save");
        SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBTNActionPerformed(evt);
            }
        });
        UserFormPanel.add(SaveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 713, -1, -1));

        jLabel3.setText("Address");
        UserFormPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 636, -1, -1));

        jLabel4.setText("College Name");
        UserFormPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 443, -1, -1));
        UserFormPanel.add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 396, 147, -1));

        jLabel5.setText("Last Name");
        UserFormPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 401, -1, -1));

        fieldCollegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCollegeNameActionPerformed(evt);
            }
        });
        UserFormPanel.add(fieldCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 438, 147, -1));

        jLabel6.setText("personalPhone");
        UserFormPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 481, -1, -1));
        UserFormPanel.add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 476, 147, -1));

        jLabel7.setText("personalEmail");
        UserFormPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 557, -1, -1));
        UserFormPanel.add(fieldStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 631, 147, -1));
        UserFormPanel.add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 552, 147, -1));

        jLabel8.setText("officePhone");
        UserFormPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 519, -1, -1));

        jLabel9.setText("officeEmail");
        UserFormPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 598, -1, -1));
        UserFormPanel.add(fieldOfficeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 593, 147, -1));
        UserFormPanel.add(fieldOfficePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 514, 147, -1));

        address2.setText("permanentAddress");
        UserFormPanel.add(address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 674, -1, -1));
        UserFormPanel.add(fieldPermanentStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 669, 147, -1));

        jSplitPane1.setLeftComponent(UserFormPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCollegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCollegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCollegeNameActionPerformed

    private void SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBTNActionPerformed
        // TODO add your handling code here:
        // logic to save the person details
        long nuid = Integer.valueOf(fieldID.getText());
        String firstName = fieldFirstName.getText();
        String lastName = fieldLastName.getText();
        String collegeName = fieldCollegeName.getText();
        long phone = Long.valueOf(fieldPhone.getText());
        long officePhone = Long.valueOf(fieldOfficePhone.getText());
        String email = fieldEmail.getText();
        String officeEmail = fieldOfficeEmail.getText();
        String permanentStreet = fieldPermanentStreet.getText();
        String street = fieldStreet.getText();

        this.person.setNUID(nuid);
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(collegeName);
        //Person obj2 = new Person();

        Address address = this.person.getAddress();
        address.setStreetName(street);

        Address permanentAddress = this.person.getPermanentAddress();
        permanentAddress.setStreetName(permanentStreet);

        Contact personalContact = this.person.getPersonalContact();
        personalContact.setPhone(phone);
        personalContact.setEmail(email);

        Contact officeContact = this.person.getOfficeContact();
        officeContact.setOfficePhone(officePhone);
        officeContact.setOfficeEmail(officeEmail);

        display();
    }//GEN-LAST:event_SaveBTNActionPerformed

    private void fieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDActionPerformed
    
    private void display() {
        viewNUID.setText(String.valueOf(this.person.getNUID()));
        viewFirstName.setText(this.person.getFirstName());
        viewLastName.setText(this.person.getLastName());
        viewCollegeName.setText(this.person.getCollegeName());
        viewStreet.setText(this.person.getAddress().getStreetName());
        viewPermanentStreet.setText(this.person.getPermanentAddress().getStreetName());
        viewPersonalPhone.setText(String.valueOf(this.person.getPersonalContact().getPhone()));
        viewOfficePhone.setText(String.valueOf(this.person.getOfficeContact().getOfficePhone()));
        viewPersonalEmail.setText(this.person.getPersonalContact().getEmail());
        viewOfficeEmail.setText(this.person.getOfficeContact().getOfficeEmail());

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBTN;
    private javax.swing.JPanel UserFormPanel;
    private javax.swing.JLabel address2;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldOfficeEmail;
    private javax.swing.JTextField fieldOfficePhone;
    private javax.swing.JTextField fieldPermanentStreet;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldStreet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewOfficeEmail;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JLabel viewPermanentStreet;
    private javax.swing.JLabel viewPersonalEmail;
    private javax.swing.JLabel viewPersonalPhone;
    private javax.swing.JLabel viewStreet;
    // End of variables declaration//GEN-END:variables
    

   
}
